# Generated by Django 5.0.2 on 2025-06-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0026_alter_allinone_n_serie_alter_allinoneadmins_n_serie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinone',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='allinoneadmins',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='azotea',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='bodegaadr',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='proyectores',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        ),
    ]
