# Generated by Django 5.0.8 on 2025-11-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0038_alter_eliminados_activo_alter_eliminados_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allinone',
            name='etiqueta',
        ),
        migrations.RemoveField(
            model_name='allinoneadmins',
            name='etiqueta',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='etiqueta',
        ),
        migrations.RemoveField(
            model_name='azotea',
            name='etiqueta',
        ),
        migrations.RemoveField(
            model_name='bodegaadr',
            name='etiqueta',
        ),
        migrations.RemoveField(
            model_name='eliminados',
            name='etiqueta',
        ),
        migrations.RemoveField(
            model_name='minipc',
            name='etiqueta',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='etiqueta',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='etiqueta',
        ),
        migrations.RemoveField(
            model_name='proyectores',
            name='etiqueta',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='etiqueta',
        ),
        migrations.AddField(
            model_name='audio',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ETIQUETA'),
        ),
        migrations.AddField(
            model_name='minipc',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ETIQUETA'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ETIQUETA'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ETIQUETA'),
        ),
        migrations.AddField(
            model_name='proyectores',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ETIQUETA'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ETIQUETA'),
        ),
        migrations.AlterField(
            model_name='allinone',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ETIQUETA'),
        ),
        migrations.AlterField(
            model_name='allinoneadmins',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ETIQUETA'),
        ),
        migrations.AlterField(
            model_name='azotea',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ETIQUETA'),
        ),
        migrations.AlterField(
            model_name='bodegaadr',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ETIQUETA'),
        ),
    ]
