# Generated by Django 5.0.8 on 2025-12-03 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0039_remove_allinone_etiqueta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinone',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='allinoneadmins',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='azotea',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='bodegaadr',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='proyectores',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta'),
        ),
        migrations.CreateModel(
            name='EquiposIsla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(max_length=150, verbose_name='Activo')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('n_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Serie')),
                ('etiqueta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta')),
                ('bdo', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=30, null=True, verbose_name='BDO')),
                ('estado', models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación')),
                ('marca', models.CharField(default='', max_length=100, verbose_name='Marca')),
                ('ubicacion', models.CharField(default='Seleccione', max_length=100, verbose_name='Ubicación')),
                ('netbios', models.CharField(blank=True, max_length=100, null=True, verbose_name='NetBIOS')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrador por')),
            ],
            options={
                'verbose_name': 'Equipos Isla',
                'verbose_name_plural': 'Equipos Islas',
                'ordering': ['ubicacion', '-fecha_creacion'],
            },
        ),
    ]
