# Generated by Django 6.0.1 on 2026-01-23 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0042_alter_equiposisla_options_eliminados_etiqueta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Televisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(max_length=150, verbose_name='Activo')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('n_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Serie')),
                ('etiqueta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta')),
                ('bdo', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=30, null=True, verbose_name='BDO')),
                ('estado', models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación')),
                ('marca', models.CharField(default='', max_length=100, verbose_name='Marca')),
                ('ubicacion', models.CharField(default='Seleccione', max_length=100, verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Televisor',
                'verbose_name_plural': 'Televisores',
                'ordering': ['ubicacion', '-fecha_creacion'],
            },
        ),

        migrations.AddField(
            model_name='televisor',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrador por'),
        ),
        migrations.AddIndex(
            model_name='televisor',
            index=models.Index(fields=['creado_por'], name='idx_televisor_creado_por'),
        ),
    ]
