# Generated by Django 6.0.1 on 2026-02-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0043_televisor_equiposisla_idx_equiposisla_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allinone',
            options={'ordering': ['ubicacion', '-fecha_creacion'], 'verbose_name': 'All In One Académico', 'verbose_name_plural': 'All In Ones Académicos'},
        ),
    ]

